services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile-Airflow
    container_name: airflow
    env_file:
      - .env
    # volumes:
    #   - ./dags:/workspaces/airflow/dags
    ports:
      - "8080:8080"
    # command: /bin/bash -c "/tmp/init-airflow.sh && airflow standalone"
    command: tail -f /dev/null

volumes:
  postgres_data:
