FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libsqlite3-dev \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /workspaces/airflow

RUN python -m venv /opt/venv
ENV PYTHONUNBUFFERED=1 \
    PATH="/opt/venv/bin:$PATH"

RUN groupadd -g 1000 airflow && \
    useradd -m -u 1000 -g 1000 -s /bin/bash airflow

COPY init-airflow.sh /tmp/init-airflow.sh
COPY entrypoint.sh /tmp/entrypoint.sh
RUN chmod +x /tmp/entrypoint.sh /tmp/init-airflow.sh

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt

ENTRYPOINT ["/tmp/entrypoint.sh"]

USER airflow
